-- Insert sample electricians (passwords are bcrypt hash for 'password123')
INSERT INTO electricians (name, phone, email, password, specialization, experience_years, location, availability_status, rating, bio, photo, certifications, services_offered, hourly_rate) VALUES
('Rajesh Kumar', '+91 98765 43210', 'rajesh.k@electroserve.in', '$2a$10$iM2vVwT5g80nQ8v.E.iW7O.v.q0Cj.qE.Bf.m.iV.w.g.5XzO.J7.', 'House Wiring', 12, 'Anna Nagar, Chennai', 'Available', 4.9, 'Certified master electrician with 12+ years of experience in residential and commercial wiring.', '', 'Licensed Electrical Contractor, TNELB Certified, Solar Panel Installation', 'House Wiring (New), EB Meter Installation, Electrical Panel Upgrade', 350.0),
('Senthil Murugan', '+91 98765 11223', 'senthil.m@electroserve.in', '$2a$10$iM2vVwT5g80nQ8v.E.iW7O.v.q0Cj.qE.Bf.m.iV.w.g.5XzO.J7.', 'AC Wiring', 15, 'T. Nagar, Chennai', 'Available', 4.8, 'Industrial and residential electrical expert. Specialized in AC installation wiring and high-voltage troubleshooting.', '', 'ITI Electrical, Industrial Electrician Grade I, AC Installation Certified', 'AC Installation Wiring, Industrial Wiring, Fault Finding', 400.0),
('Mohammed Farhan', '+91 98765 22334', 'farhan.m@electroserve.in', '$2a$10$iM2vVwT5g80nQ8v.E.iW7O.v.q0Cj.qE.Bf.m.iV.w.g.5XzO.J7.', 'Solar Panel', 8, 'Velachery, Chennai', 'Unavailable', 4.7, 'Specialist in solar panel installation and smart home automation.', '', 'Solar PV Installation, Smart Home Certified', 'Solar Panel Installation, Inverter Setup, Smart Home Wiring', 450.0),
('Vignesh Babu', '+91 98765 33445', 'vignesh.b@electroserve.in', '$2a$10$iM2vVwT5g80nQ8v.E.iW7O.v.q0Cj.qE.Bf.m.iV.w.g.5XzO.J7.', 'Repairs', 6, 'Adyar, Chennai', 'Available', 4.6, 'Quick-response electrician for emergency repairs and routine maintenance.', '', 'ITI Electrical, Emergency Response Trained', 'Emergency Repair, Switch & Socket Repair', 300.0);

-- Insert sample customer
INSERT INTO customers (name, email, phone, address, password, created_at) VALUES
('Test Customer', 'customer@test.com', '9876543210', 'Chennai', '$2a$10$iM2vVwT5g80nQ8v.E.iW7O.v.q0Cj.qE.Bf.m.iV.w.g.5XzO.J7.', CURRENT_TIMESTAMP());

-- Insert sample reviews
INSERT INTO reviews (customer_id, electrician_id, rating, comment, review_date) VALUES
(1, 1, 5, 'Excellent work on our entire house rewiring. Very professional.', CURRENT_TIMESTAMP()),
(1, 2, 5, 'Best electrician for AC installation. Neat work.', CURRENT_TIMESTAMP()),
(1, 3, 4, 'Smart home automation was done well.', CURRENT_TIMESTAMP());

-- Insert sample plumbers (passwords are bcrypt hash for 'password123')
INSERT INTO plumbers (name, phone, email, password, specialization, experience_years, location, availability_status, rating, bio, photo, certifications, services_offered, hourly_rate) VALUES
('Arun Prakash', '+91 98765 55001', 'arun.p@electroserve.in', '$2a$10$iM2vVwT5g80nQ8v.E.iW7O.v.q0Cj.qE.Bf.m.iV.w.g.5XzO.J7.', 'Pipe Repair', 10, 'Anna Nagar, Chennai', 'Available', 4.8, 'Expert plumber with 10+ years in residential and commercial pipe repair and installation. Quick turnaround on emergency calls.', '', 'Licensed Plumber, ITI Plumbing, Leak Detection Certified', 'Pipe Repair, Leak Fixing, New Pipe Installation, Emergency Plumbing', 300.0),
('Karthik Rajan', '+91 98765 55002', 'karthik.r@electroserve.in', '$2a$10$iM2vVwT5g80nQ8v.E.iW7O.v.q0Cj.qE.Bf.m.iV.w.g.5XzO.J7.', 'Bathroom Fitting', 14, 'T. Nagar, Chennai', 'Available', 4.9, 'Specialist in complete bathroom renovation, modern fixture fitting, and kitchen plumbing. Known for clean, precise work.', '', 'Master Plumber, Bathroom Design Certified, CIPET Certified', 'Bathroom Fitting, Kitchen Plumbing, Toilet Installation, Shower Setup', 400.0),
('Deepak Sundar', '+91 98765 55003', 'deepak.s@electroserve.in', '$2a$10$iM2vVwT5g80nQ8v.E.iW7O.v.q0Cj.qE.Bf.m.iV.w.g.5XzO.J7.', 'Water Heater', 7, 'Velachery, Chennai', 'Unavailable', 4.6, 'Geyser and water heater specialist. Experienced in solar water heater installation and repair for all major brands.', '', 'ITI Plumbing, Solar Water Heater Certified', 'Geyser Installation, Water Heater Repair, Solar Water Heater Setup', 350.0),
('Manikandan V.', '+91 98765 55004', 'manikandan.v@electroserve.in', '$2a$10$iM2vVwT5g80nQ8v.E.iW7O.v.q0Cj.qE.Bf.m.iV.w.g.5XzO.J7.', 'Drainage', 9, 'Adyar, Chennai', 'Available', 4.7, 'Drainage and sewer line expert. Fast response for clogged drains, overflow issues, and underground pipe work.', '', 'Licensed Plumber, Drainage Specialist Certified, Emergency Response Trained', 'Drain Cleaning, Sewer Repair, Clog Removal, Underground Pipe Work', 280.0),
('Suresh Krishnan', '+91 98765 55005', 'suresh.k@electroserve.in', '$2a$10$iM2vVwT5g80nQ8v.E.iW7O.v.q0Cj.qE.Bf.m.iV.w.g.5XzO.J7.', 'Leak Detection', 11, 'Porur, Chennai', 'Available', 4.8, 'Leak detection specialist using modern equipment. Experienced in hidden pipe leak identification and waterproofing.', '', 'Licensed Plumber, Advanced Leak Detection, Waterproofing Certified', 'Leak Detection, Hidden Pipe Repair, Waterproofing, Water Damage Restoration', 380.0),
('Balaji Murugesan', '+91 98765 55006', 'balaji.m@electroserve.in', '$2a$10$iM2vVwT5g80nQ8v.E.iW7O.v.q0Cj.qE.Bf.m.iV.w.g.5XzO.J7.', 'Kitchen Plumbing', 8, 'Tambaram, Chennai', 'Available', 4.5, 'Kitchen plumbing expert. Specializes in sink installation, RO system setup, and dishwasher connections.', '', 'ITI Plumbing, Kitchen Fitout Certified', 'Kitchen Sink, RO Setup, Dishwasher Connection, Garbage Disposal', 320.0),
('Prasad Venkatesh', '+91 98765 55007', 'prasad.v@electroserve.in', '$2a$10$iM2vVwT5g80nQ8v.E.iW7O.v.q0Cj.qE.Bf.m.iV.w.g.5XzO.J7.', 'Emergency', 13, 'Mylapore, Chennai', 'Available', 4.9, '24/7 emergency plumber with 13+ years of experience. Fastest response time in Chennai for burst pipes and flooding.', '', 'Master Plumber, Emergency Response Certified, Commercial Plumbing Licensed', 'Emergency Repair, Burst Pipe, Flood Control, Commercial Plumbing', 500.0),
('Dinesh Kumar S.', '+91 98765 55008', 'dinesh.s@electroserve.in', '$2a$10$iM2vVwT5g80nQ8v.E.iW7O.v.q0Cj.qE.Bf.m.iV.w.g.5XzO.J7.', 'Water Tank', 6, 'Sholinganallur, Chennai', 'Available', 4.4, 'Water tank installation and cleaning specialist. Expert in overhead and underground tank systems for residential complexes.', '', 'ITI Plumbing, Tank Cleaning Certified', 'Tank Installation, Tank Cleaning, Pump Repair, Pipeline Setup', 260.0);

